// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIWorldCities.Data;

#nullable disable

namespace WebAPIWorldCities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129085659_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.WorldCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("WorldCities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Gdansk",
                            Country = "Poland",
                            Population = 487370
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Malmö",
                            Country = "Sweden",
                            Population = 339320
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Bergen",
                            Country = "Norway",
                            Population = 294029
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
