// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIWorldCities.Data;

#nullable disable

namespace WebAPIWorldCities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130091847_AddCountryTable")]
    partial class AddCountryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.WorldCity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("WorldCities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "",
                            CountryId = 3,
                            Population = 487370
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "",
                            CountryId = 1,
                            Population = 339320
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "",
                            CountryId = 4,
                            Population = 294029
                        });
                });

            modelBuilder.Entity("WebAPIWorldCities.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = ""
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = ""
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = ""
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = ""
                        });
                });

            modelBuilder.Entity("Models.WorldCity", b =>
                {
                    b.HasOne("WebAPIWorldCities.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebAPIWorldCities.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
